<?php

namespace boxiweb\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
 
/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends EntityRepository
{
     public function counter() {
        $qb = $this->createQueryBuilder('u')->select('COUNT(u)');
  
        return $qb->getQuery()->getSingleScalarResult();
    }
}
 