services:
#    boxiweb_user.example:
#        class: boxiweb\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    boxiweb.form.registration:
        class: boxiweb\UserBundle\Form\RegistrationType
#        arguments: ["@security.context", "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias : boxiweb_user_registration }
    login_listener:
        class: boxiweb\UserBundle\Listener\LoginListener
        arguments: ['@fos_user.user_manager']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login' }
            - { name: 'kernel.listener', event: 'fos_user.security.implicit_login' }
    menu.voter.request:
        class: boxiweb\UserBundle\Menu\RequestVoter
        arguments: [ @request_stack ]
        tags:
            - { name: knp_menu.voter, alias: main }  
            
            
    app.menu_builder:
       class: boxiweb\UserBundle\Menu\MenuBuilder
       arguments: ["@knp_menu.factory"]

    app.main_menu:
       class: Knp\Menu\MenuItem 
       factory: ["@app.menu_builder", createMainMenu]
       arguments: ["@request_stack"]
       tags:
           - { name: knp_menu.menu, alias: main }
       